# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'
  inhibit_all_warnings!
  use_frameworks!

post_install do |installer|
  installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
             end
        end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

# 使用源码环境
# 参数: 组件名称、是否源码、是否清理
def self.use_env_source(component, isSource, isClean)
  print('**** begin use_env_source: ', component, ' ****')
  puts('')
  
  if isSource
    # 拼装_Source，设置环境变量为源码
    source = component + '_Source'
    ENV[source] = '1'
  end
  
  if isClean
    # 拼接命令，清理本地对应的缓存
    command = 'pod cache clean --all ' + component
    puts(command)
    system command
    
    # 清理Pods目录下的组件
    puts('clear ./Pods/' + component)
    command = 'rm -rf ./Pods/' + component
    system command
  end
  
  print('**** end use_env_source: ', component, ' ****')
  puts('')
end

use_env_source('LCOpenMediaSDK', true, false)

target 'LeChangeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#  pod 'KVOController', '~> 1.2.0'
#  pod 'ZXingObjC', '~> 3.2.1'
#  pod 'SnapKit'
#  pod 'SDWebImage', '~> 5.0.3'
#  pod 'MJRefresh', '~> 3.7.5'
#  pod 'Masonry'
#  pod 'AFNetworking'
#  pod 'MBProgressHUD', '1.0.0'
#  pod 'ObjectMapper', '~> 3.5.3'
#  pod 'MJExtension'
#  pod 'SAMKeychain', '~> 1.5.3'
#  pod 'GTMBase64', '~> 1.0.1'
  # Pods for LeChangeDemo
  # pod 'LCOpenSDK', '~> 3.12.06'
  

end
