# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'
  inhibit_all_warnings!
  use_frameworks!

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ARCHS'] = 'arm64'
#      config.build_settings['VALID_ARCHS'] = 'arm64'
#    end
#  end
#end

target 'LeChangeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'KVOController', '~> 1.2.0'
  pod 'ZXingObjC', '~> 3.2.1'
  pod 'SnapKit'
  pod 'SDWebImage', '~> 5.0.3'
  pod 'MJRefresh', '~> 3.7.5'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'MBProgressHUD', '1.0.0'
  pod 'ObjectMapper', '~> 3.5.3'
  pod 'MJExtension'
  pod 'SAMKeychain', '~> 1.5.3'
  pod 'GTMBase64', '~> 1.0.1'
  # Pods for LeChangeDemo
  pod 'LCOpenSDK', '~> 3.12.02'

end
