// Generated by Apple Swift version 5.5.2 effective-4.1.50 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef LCADDDEVICEMODULE_SWIFT_H
#define LCADDDEVICEMODULE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import LCBaseModule;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LCAddDeviceModule",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


typedef SWIFT_ENUM(NSInteger, CodeType, closed) {
  CodeTypeSuccess = 200,
  CodeTypeParseQRCodeFail = 201,
  CodeTypeConnectCloudTimeOut = 202,
  CodeTypeFindDevFail = 203,
  CodeTypeConnectAPFail = 204,
  CodeTypeBindByMe = 205,
  CodeTypeBingByOther = 206,
  CodeTypeInputScError = 207,
  CodeTypeBoxExisted = 208,
  CodeTypeBoxOffline = 209,
  CodeTypeOtherCode = 500,
};


SWIFT_CLASS("_TtC17LCAddDeviceModule21DHAddDeviceLogManager")
@interface DHAddDeviceLogManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DHAddDeviceLogManager * _Nonnull shareInstance;)
+ (DHAddDeviceLogManager * _Nonnull)shareInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DHAddDeviceLogModel;

@interface DHAddDeviceLogManager (SWIFT_EXTENSION(LCAddDeviceModule))
/// 开始添加设备log
/// 1、QRCode：扫码添加
/// 2、SN：手输序列号添加
/// 3、NetworkConfig：离线配网
/// result: inputData
- (void)addDeviceStartLogWithModel:(DHAddDeviceLogModel * _Nonnull)model;
/// 添加/配网流程结束log
- (void)addDeviceEndLogWithModel:(DHAddDeviceLogModel * _Nonnull)model;
/// NetSDK接口调用结果,会上报多次，每次数据均保留；(搜索接口只报失败)
- (void)addDeviceNetSDKLogWithModel:(DHAddDeviceLogModel * _Nonnull)model;
/// 初始化结果，会上报多次，每次数据均保留(IOS 新设备IP无效时单独调)
- (void)addDeviceInitLogWithModel:(DHAddDeviceLogModel * _Nonnull)model;
@end

@class NSString;
@class NSNumber;
@class DHDeviceInfoLogModel;

SWIFT_CLASS("_TtC17LCAddDeviceModule19DHAddDeviceLogModel")
@interface DHAddDeviceLogModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull inputData;
@property (nonatomic, copy) NSString * _Nonnull did;
@property (nonatomic, readonly, copy) NSString * _Nonnull time;
@property (nonatomic, copy) NSString * _Nonnull res;
@property (nonatomic) NSInteger errCode;
@property (nonatomic, copy) NSString * _Nonnull dese;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull method;
@property (nonatomic, strong) DHDeviceInfoLogModel * _Nonnull deviceInfo;
@property (nonatomic, readonly, copy) NSString * _Nonnull resFail;
@property (nonatomic, readonly, copy) NSString * _Nonnull initDev;
- (NSString * _Nonnull)initDev SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull initDevByIP;
- (NSString * _Nonnull)initDevByIP SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum DHNetConfigMode : NSInteger;
enum DHNetConnectType : NSInteger;

SWIFT_CLASS("_TtC17LCAddDeviceModule18DHAddDeviceManager")
@interface DHAddDeviceManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DHAddDeviceManager * _Nonnull sharedInstance;)
+ (DHAddDeviceManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSString * _Nonnull deviceId;
@property (nonatomic, copy) NSString * _Nonnull deviceModel;
/// 二维码型号
@property (nonatomic, copy) NSString * _Nullable deviceQRCodeModel;
/// 市场型号
@property (nonatomic, copy) NSString * _Nullable deviceMarketModel;
/// imei码【扫描解析出来】
@property (nonatomic, copy) NSString * _Nonnull imeiCode;
/// 设备安全码【国内需要，扫描解析出来】
@property (nonatomic, copy) NSString * _Nullable regCode;
/// NC吗【扫描解析出来】
@property (nonatomic, copy) NSString * _Nullable ncCode;
/// 配网模式
@property (nonatomic) enum DHNetConfigMode netConfigMode;
/// 是否是扫码进入
@property (nonatomic) BOOL isEnterByQrcode;
/// 网络连接类型
@property (nonatomic) enum DHNetConnectType ncType;
/// 设备初始化的密码
@property (nonatomic, copy) NSString * _Nonnull initialPassword;
@property (nonatomic, copy) NSString * _Nullable wifiSSID;
@property (nonatomic, copy) NSString * _Nullable wifiPassword;
/// 是否从离线配网入口进入
@property (nonatomic) BOOL isEntryFromWifiConfig;
/// 能力集
@property (nonatomic, copy) NSString * _Nonnull abilities;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 判断当前的添加的设备，是否已经在局域网搜索到
- (BOOL)isDeviceFindInLocalNetwork SWIFT_WARN_UNUSED_RESULT;
@end


@class NSCoder;

SWIFT_CLASS("_TtC17LCAddDeviceModule13DHAppWifiCell")
@interface DHAppWifiCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17LCAddDeviceModule18DHAutoKeyboardView")
@interface DHAutoKeyboardView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end

@protocol DHCycleTimerViewDelegate;
@class UIColor;

SWIFT_CLASS("_TtC17LCAddDeviceModule16DHCycleTimerView")
@interface DHCycleTimerView : UIView
@property (nonatomic, weak) id <DHCycleTimerViewDelegate> _Nullable delegate;
/// 超时的闭包，外层需要注意循环引用的问题
@property (nonatomic, copy) void (^ _Nullable timeout)(void);
/// 线条宽度
@property (nonatomic) CGFloat progressWidth;
/// 进度条底色
@property (nonatomic, strong) UIColor * _Nonnull progressBackgroundColor;
/// 进度条前景颜色
@property (nonatomic, strong) UIColor * _Nonnull progressForegroundColor;
/// 倒计时总时间
@property (nonatomic) NSInteger maxTime;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)startTimer;
- (void)stopTimer;
- (void)pauseTimer;
- (void)resumeTimer;
@end


SWIFT_PROTOCOL("_TtP17LCAddDeviceModule24DHCycleTimerViewDelegate_")
@protocol DHCycleTimerViewDelegate <NSObject>
- (void)cycleTimerViewTimeoutWithCycleView:(DHCycleTimerView * _Nonnull)cycleView;
- (void)cycleTimerViewWithCycleView:(DHCycleTimerView * _Nonnull)cycleView tick:(NSInteger)tick;
@end

typedef SWIFT_ENUM(NSInteger, DHDeviceAccessType, closed) {
  DHDeviceAccessTypeP2p = 0,
  DHDeviceAccessTypeEasy4ip = 1,
  DHDeviceAccessTypePaas = 2,
};


SWIFT_CLASS("_TtC17LCAddDeviceModule20DHIntroductionParser")
@interface DHIntroductionParser : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


/// 配网类型
typedef SWIFT_ENUM(NSInteger, DHNetConfigMode, closed) {
  DHNetConfigModeWifi = 0,
  DHNetConfigModeWired = 1,
  DHNetConfigModeSoftAp = 2,
  DHNetConfigModeSimCard = 3,
  DHNetConfigModeQrCode = 4,
  DHNetConfigModeLocal = 5,
/// < 猫眼类只支持本地配网
  DHNetConfigModeNbIoT = 6,
/// < NB
  DHNetConfigModeBle = 7,
};

typedef SWIFT_ENUM(NSInteger, DHNetConfigStrategy, closed) {
  DHNetConfigStrategyDefalult = 0,
  DHNetConfigStrategyFromOMS = 1,
  DHNetConfigStrategyFromNC = 2,
};

/// 网络连接类型：对应NC码
typedef SWIFT_ENUM(NSInteger, DHNetConnectType, closed) {
/// 没有NC码的
  DHNetConnectTypeNone = 0,
/// 旧的声波算法
  DHNetConnectTypeSoundWave = 1,
/// 优化声波算法
  DHNetConnectTypeSoundWaveV2 = 2,
/// 软AP
  DHNetConnectTypeSoftAp = 3,
/// 蓝牙
  DHNetConnectTypeBuleTooth = 4,
};


SWIFT_PROTOCOL("_TtP17LCAddDeviceModule26DHOMSConfigManagerProtocol_")
@protocol DHOMSConfigManagerProtocol <DHServiceProtocol>
/// 清除OMS缓存
- (void)clearOMSCache;
/// 获取OMS缓存路径
- (NSString * _Nonnull)cacheFolderPath SWIFT_WARN_UNUSED_RESULT;
/// 按市场型号检查/更新引导信息
- (void)checkUpdateIntrodutionByMarketModel:(NSString * _Nonnull)model;
/// 检查/更新设备型号
- (void)checkUpdateDeviceModels;
/// 预加载部分型号
- (void)preloadIntroductions;
@end


SWIFT_PROTOCOL("_TtP17LCAddDeviceModule27DHOfflineWifiConfigProtocol_")
@protocol DHOfflineWifiConfigProtocol <DHServiceProtocol>
/// 根据设备id和设备密码更新服务端的设备密码
/// \param deviceId 设备id
///
/// \param devicePassword 设备密码
///
- (void)updateDeviceInfoWithDeviceId:(NSString * _Nonnull)deviceId byPassword:(NSString * _Nonnull)devicePassword;
/// 保存设备密码至本地缓存
/// \param deviceId 设备id
///
/// \param password 设备密码
///
- (void)savePasswordInCacheWithDeviceId:(NSString * _Nonnull)deviceId password:(NSString * _Nonnull)password;
/// 成功后跳转处理：海外至主页
- (void)backToMainController;
@end



SWIFT_CLASS("_TtC17LCAddDeviceModule17LCAddDeviceModule")
@interface LCAddDeviceModule : NSObject <DHModuleProtocol>
- (void)moduleInit;
- (void)moduleCustomEvent:(NSString * _Null_unspecified)eventname userInfo:(NSDictionary * _Null_unspecified)userInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
